CREATE TABLE IF NOT EXISTS `users` (
    `id` BINARY(16) NOT NULL PRIMARY KEY,
    `display_id` VARCHAR(32) NOT NULL UNIQUE,
    `name` VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS `user_passwords` (
    `user_id` BINARY(16) NOT NULL PRIMARY KEY,
    `psk` VARCHAR(128) NOT NULL
);
