name: login-with-axum

services:

  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MARIADB_USER=${MYSQL_USER:-db}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD:-fakepassword}
      - MARIADB_DATABASE=${MYSQL_DATABASE:-db}
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
      tags:
        - login-with-axum
      target: debian-slim
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-db}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-fakepassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=3306
      - PREFIX=${PREFIX:-}
      - JWT_ISSUER=${JWT_ISSUER:-login-with-axum}
      - JWT_KEY=${JWT_KEY:-loginwithaxum}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4176:${PORT:-4176}
